#!/usr/bin/env python2

from PyQt4 import QtCore, QtGui
from NSMGitServer import *
from NSMGitUI import *
import time

class Main:
    def __init__(self):
        self.nsm_git_thread = QtCore.QThread()
        self.nsm_git = NSMGitServerThread()
        self.nsm_git.moveToThread(self.nsm_git_thread)
        self.nsm_git_thread.started.connect(self.nsm_git.run)
        self.nsm_git_thread.start()
        
        while not self.nsm_git.server:
            time.sleep(1)

        self.ui = NSMGitUI()
        self.ui.closed.connect(self.windowClosed)
        self.nsm_git.server.loaded.connect(self.initUI)
        self.nsm_git.server.ui_visible.connect(self.ui.setVisible)
        self.nsm_git.server.handshake()

    def initUI(self, repo):
        self.ui.initUI(str(repo))

    def windowClosed(self):
        self.nsm_git.server.hide_gui_callback()

if __name__ == '__main__':
    import sys

    app = QtGui.QApplication(sys.argv)
    main = Main()

    sys.exit(app.exec_())
